### ISSUE TITLE
Region and RegionProvider Iterators

### ISSUE THREAD

**Issue by zettymaster** [eihwaz/anvil-region#11]
Since Regions may contain chunks or entire regions that have not been generated yet, having Iterators over both the RegionProviders and the Regions themselves is something I'm missing right now.

Trial and error is just slow (iterating over the entire 32bits in both X and Z for regions) and fetching the list of generated files and passing in only the existing ones may work but defeats the purpose of having a provider.

I'd be happy to make an implementation, just leaving this here to get your thoughts on possible implementations (I want to avoid pulling something like Regex and patterns are still experimental). A bit of a warning though: I'm still new to Rust...

**Comment by zettymaster** [comment]
Specifically if Chunks that have not been generated yet should be skipped or if they should just error and leave the skipping to the user I am unsure about.

**Comment by vaIgarashi** [comment]
Region maximum coordinates are limited to world coordinates - 2^27 (2^32/32).

1. The best way to find all regions is to loop over the region folder and extract the region coordinates from the file names. `r.X.Z.mca`.
2. Finding chunks inside region is a more difficult task. Upon [region load](https://github.com/eihwaz/anvil-region/blob/master/src/region.rs#L104) we read information about chunks inside region to [metadata](https://github.com/eihwaz/anvil-region/blob/master/src/region.rs#L36). The existing chunks will return false on [is_empty](https://github.com/eihwaz/anvil-region/blob/master/src/region.rs#L359). I think best way to write reverse function [from metadata index to RegionChunkPosition](https://github.com/eihwaz/anvil-region/blob/master/src/position.rs#L41). The final strategy is to iterate over chunks metadata, filter all non empty, convert index to coordinate and call for every chunk [read_chunk](https://github.com/eihwaz/anvil-region/blob/master/src/region.rs#L127)

Contributions are welcome :) What are you working on?

**Comment by zettymaster** [comment]
I'm working on a little tool to find specific blocks (for now only tile entities, later any) in a world. Nothing really special, but i desperately need practice in rust.

Edit: Hooo boy, my rust is TERRIBLE! I'm trying to implement FolderRegionProviderIterator and end up getting caught up in all kinds of confusion.

**Comment by vaIgarashi** [comment]
Just add a new method to RegionProvider and imlement it :) Let me know if you would like me to add new methods.

**Comment by zettymaster** [comment]
Sooo at the moment I don't really see a way to have statically dispatched Iterators on the RegionProviders due to the fact that they are implemented as a trait. So we always have to use dynamic dispatch `-> Box<Iterator<...>>`

I'm also genuinely questioning if it is even necessary to have a `RegionProvider` trait, when the only implementation of it is the Folder one. Like what are the potential use cases here? Queries from databases? But that does not make sense either, you'd need comparatively gigantic Blob columns to make that work... The conventional wisdom of "we can mock it out when testing" isn't applying here either, folders are as bare as it gets anyway...

Anyway, what are your thoughts on this? I'd maybe move `FolderRegionProvider` into `RegionProvider` to minimize the changes to existing code, so just the referenced struct name has to change from a library user's perspective.

(Sorry if that sounded more rude then necessary, I'm just trying to relay my thoughts)

**Comment by vaIgarashi** [comment]
In rust we have ad-hoc polymorphism and each implementation should have own implementation of trait. This mean, that you need to implement `Iterator` trait directly on `FolderRegionProvider`. The motivation for trait came from #4. No worries. I dont think that you are rude :)
