### ISSUE TITLE
Chunk corruption when compressed size is >4096 bytes

### ISSUE THREAD

**Issue by SpenceSellers** [eihwaz/anvil-region#6]
First off, this project is awesome.

I'm using it to build a custom map generator, but the worlds I generate are getting corrupted. I've narrowed it down to happening when **you save a chunk that compresses to a size greater than 4096 bytes**. I looked through the code in this project but I haven't nailed down an actual cause yet.

[Here's some code that reproduces the problem](https://gist.github.com/SpenceSellers/85de2936243f76af0bafb8e952e8f7c1). I haven't been able to narrow it down more than that, so it's still sort of gross.

Here's the output with chunk sizes > 4096 bytes:
```
Saving chunk 0,0
Compressed size: 4568 bytes
Saving chunk 0,1
Compressed size: 4568 bytes
Saving chunk 0,2
Compressed size: 4568 bytes
Saving chunk 1,0
Compressed size: 4568 bytes
Saving chunk 1,1
Compressed size: 4568 bytes
Corrupted chunk: 23,0: LengthExceedsMaximum { length: 4569, maximum_length: 4096 }
Saving chunk 1,2
Compressed size: 4568 bytes
Corrupted chunk: 23,0: LengthExceedsMaximum { length: 4569, maximum_length: 4096 }
Saving chunk 2,0
Compressed size: 4568 bytes
Corrupted chunk: 23,0: LengthExceedsMaximum { length: 4569, maximum_length: 4096 }
Saving chunk 2,1
Compressed size: 4568 bytes
Corrupted chunk: 23,0: LengthExceedsMaximum { length: 4569, maximum_length: 4096 }
Corrupted chunk: 23,1: LengthExceedsMaximum { length: 4569, maximum_length: 4096 }
Saving chunk 2,2
Compressed size: 4568 bytes
Corrupted chunk: 0,3: LengthExceedsMaximum { length: 4569, maximum_length: 4096 }
Corrupted chunk: 23,0: LengthExceedsMaximum { length: 4569, maximum_length: 4096 }
Corrupted chunk: 23,1: LengthExceedsMaximum { length: 4569, maximum_length: 4096 }

Process finished with exit code 0
```
Minecraft agrees that the listed chunks are corrupted and spits out errors. 

And here's the output with a chunk size < 4096 bytes (No chunks are corrupted):
```
Saving chunk 0,0
Compressed size: 3068 bytes
Saving chunk 0,1
Compressed size: 3068 bytes
Saving chunk 0,2
Compressed size: 3068 bytes
Saving chunk 1,0
Compressed size: 3068 bytes
Saving chunk 1,1
Compressed size: 3068 bytes
Saving chunk 1,2
Compressed size: 3068 bytes
Saving chunk 2,0
Compressed size: 3068 bytes
Saving chunk 2,1
Compressed size: 3068 bytes
Saving chunk 2,2
Compressed size: 3068 bytes

Process finished with exit code 0
```

I notice that the chunks that are getting corrupted are _not_ always the ones that are actually being written, strangely enough.

**Comment by vaIgarashi** [comment]
Hi! Thanks for submitting issue with reproducer. I tested it with my save and none chunks were corrupted. Can you share your save?

**Comment by SpenceSellers** [comment]
[EmptyWorld.zip](https://github.com/eihwaz/anvil-region/files/4943016/EmptyWorld.zip)

Here's the world. It's generated from snapshot 20w29a (Which might be the whole problem I guess).

**Comment by vaIgarashi** [comment]
Looks like `update_metadata` method not working correctly. Read chunk returns metadata from wrong chunk. I will investigate the problem more tomorrow (5am local time). Thanks for your save.

**Comment by vaIgarashi** [comment]
The issue is fixed and new version published to crates.io. Thanks!

**Comment by SpenceSellers** [comment]
Excellent! I can now generate very complex chunks no problem!
![image](https://user-images.githubusercontent.com/5377932/87884327-8bdcb080-c9d3-11ea-8082-e8c89c69adf5.png)
